[package]
name = "kickoff"
version = "0.1.0"
authors = ["Folke Gleumes <folke-kickoff@gleumes.org>"]
edition = "2018"
description = "Fast and minimal program launcher"

[dependencies]
wayland-client = "0.28.2"
smithay-client-toolkit = "0.12.0"
byteorder = "1.3.4"
rusttype = "0.9.2"
image = "0.23.11"
is_executable = "0.1.2"
fuzzy-matcher = "*"
nix = "0.19.1"
shellwords = "1.1.0"
clap = "2.33.3"
css-color = "0.1"
exec = "0.3.1"
xdg = "2.2.0"
font-loader = "0.11.0"
