[package]
name = "kickoff"
version = "0.3.1"
authors = ["Folke Gleumes <folke-kickoff@gleumes.org>"]
edition = "2018"
description = "Fast and minimal program launcher"
license = "GPL-3.0-or-later"

[dependencies]
wayland-client = "0.28.2"
smithay-client-toolkit = "0.12.0"
rusttype = "0.9.2"
image = "0.23.11"
is_executable = "0.1.2"
fuzzy-matcher = "*"
nix = "0.19.1"
shellwords = "1.1.0"
css-color = "0.1"
exec = "0.3.1"
xdg = "2.2.0"
font-loader = "0.11.0"
confy = "0.4.0"
serde = { version = "1.0.118", features = ["derive"] }
hex = "0.4.2"
futures = "0.3.8"
smithay-clipboard = "0.6.2"

[profile.release]
lto = true