[package]
name = "wini-launcher"
version = "0.1.0"
authors = ["Folke Gleumes <folke@gleumes.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wayland-client = "0.28.2"
smithay-client-toolkit = "0.12.0"
byteorder = "1.3.4"
rusttype = "0.9.2"
image = "0.23.11"
is_executable = "0.1.2"
fuzzy-matcher = "*"
nix = "0.19.1"