[package]
name = "kickoff"
version = "0.4.4"
authors = ["Folke Gleumes <folke-kickoff@gleumes.org>"]
edition = "2018"
description = "Fast and minimal program launcher"
license = "GPL-3.0-or-later"
homepage = "https://github.com/j0ru/kickoff"
repository = "https://github.com/j0ru/kickoff"
readme = "README.md"

[dependencies]
wayland-client = "0.29.0"
smithay-client-toolkit = "0.14.0"
fontdue = "0.5.2"
image = "0.23.14"
fuzzy-matcher = "0.3.7"
nix = "0.22.0"
shellwords = "1.1.0"
css-color = "0.1.1"
exec = "0.3.1"
xdg = "2.2.0"
font-loader = "0.11.0"
toml = "0.5.8"
serde = { version = "1.0.127", features = ["derive"] }
hex = "0.4.3"
futures = "0.3.16"
smithay-clipboard = "0.6.4"

[profile.release]
lto = true